### ISSUE TITLE
Specify height in [size] attribute

### ISSUE THREAD

**Issue by wjbarber3** [achwilko/ngx-svg-icon#1]
Hi, thank for the great package.  How can I specify the height of the svg when using the [size] attribute in the <svg-icon> tag.  Currently, I can only add one value which gives me an svg with square dimensions.  All of my svg are not equal in width and height.  How can I accomplish this?

**Comment by achwilko** [comment]
Hi @wjbarber3, thanks for using the package.

Unfortunately, you can't specify the height or width.  As you mentioned, you can only adjust "size" prop value which is recommended way for the icons to keep their square ratio. If your icon is not a square then use tool (free and online) like [designer.io](https://designer.io/) to modify / adjust its canvas / viewBox to be square sized. For more icons examples, visit sites like [material icons](https://material.io/icons) or [ionic icon](http://ionicons.com/) to explore different square ratio bases.
