### ISSUE TITLE
Angular 5: ngx-svg-icon\src\app\ngx-svg-icon\index.ts is not part of the compilation output.

### ISSUE THREAD

**Issue by JohnyMemony** [achwilko/ngx-svg-icon#2]
When I try to compile my application, I am getting this error:

./node_modules/ngx-svg-icon/src/app/ngx-svg-icon/index.ts
Module build failed: Error: *\node_modules\ngx-svg-icon\src\app\ngx-svg-icon\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (*\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (*\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./src/app/app.module.ts 24:0-48
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Versions**
Angular CLI: 1.5.0
Angular: 5.0.1

**Comment by LiuuY** [comment]
@JohnyMemony 

["libraries should never ship their source .ts files"](https://github.com/angular/angular-cli/issues/8284) 

so you need to compile "ngx-svg-icon\src\app\ngx-svg-icon\index.ts",

in your tsconfig.json,
```
{
  "compilerOptions": {
   ...
  },
  "include": ["src", "./node_modules/ngx-svg-icon/index.ts"] // <- add this
```

**Comment by JohnyMemony** [comment]
Thank you. It was help me.

**Comment by LiuuY** [comment]
@JohnyMemony 

You should also include ngx-svg-icon in tsconfig.spec.json
